# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPComputeExternalIpAccessConstraintV2
metadata:
  name: forbid_external_ip
  annotations:
    # This constraint is not certified by CIS.
    bundles.validator.forsetisecurity.org/cis-v1.1: 4.08
    description: Checks if Compute Engine instances have public IPs.
spec:
  severity: high
  parameters:
    # modes can be [allowlist, denylist]
    mode: denylist
    # match_mode can be [exact, regex], default is exact.
    match_mode: regex
    instances: []
    # regex example:
    - //compute.googleapis.com/projects/event-stream-staging/.*
    - //compute.googleapis.com/projects/mindvalley-event-stream/.*
    - //compute.googleapis.com/projects/mv-brain/.*
    - //compute.googleapis.com/projects/mv-dev-ricardo/.*
    - //compute.googleapis.com/projects/mv-etl-staging/.*
    - //compute.googleapis.com/projects/mv-gdrive-portal/.*
    - //compute.googleapis.com/projects/mv-page-builder-stg/.*
    - //compute.googleapis.com/projects/mv-prod-careers/.*
    - //compute.googleapis.com/projects/mv-prod-linode/.*
    - //compute.googleapis.com/projects/mv-prod-stories/.*
    - //compute.googleapis.com/projects/mv-stg-applications-hub/.*
    - //compute.googleapis.com/projects/mv-stg-brain/.*
    - //compute.googleapis.com/projects/mv-stg-stories/.*
    
    # exact match example:
    # - //compute.googleapis.com/projects/mv-dev-ricardo/zones/us-east1-b/instances/vm-external-ip

